-- auction-service 초기 스키마.
-- 주의: 컬럼명/타입/nullable은 엔티티(JPA)와 정확히 맞아야 ddl-auto=validate 부팅이 통과한다.
--       부팅 시 validate 오류가 나면 해당 엔티티 필드에 맞춰 조정할 것.
-- territoryId·bidderId·winnerId 등은 다른 서비스의 ID를 값으로만 참조(FK 없음).

-- 컬럼명은 Hibernate 네이밍(coordX→coordx, continentName→continent_name)에 맞춤.
CREATE TABLE auctions (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_id             BIGINT        NOT NULL,
    coordx                   INTEGER       NOT NULL,
    coordy                   INTEGER       NOT NULL,
    continent_name           VARCHAR(255)  NOT NULL,
    continent_id             BIGINT,
    grade                    VARCHAR(255)  NOT NULL,
    current_price            INTEGER       NOT NULL,
    current_bidder_id        BIGINT,
    current_bidder_nickname  VARCHAR(255),
    start_at                 TIMESTAMP     NOT NULL,
    end_at                   TIMESTAMP     NOT NULL,
    max_extend_until         TIMESTAMP     NOT NULL,
    settled                  BOOLEAN       NOT NULL DEFAULT FALSE
);

CREATE TABLE auction_bids (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id       BIGINT      NOT NULL REFERENCES auctions(id),
    bidder_id        BIGINT,                 -- NULL = 시스템(시작가)
    bidder_nickname  VARCHAR(50),
    price            INTEGER     NOT NULL,
    bid_at           TIMESTAMP   NOT NULL
);

CREATE INDEX idx_auction_bids_auction_bid_at ON auction_bids (auction_id, bid_at);

CREATE TABLE auction_histories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_id    BIGINT      NOT NULL REFERENCES auctions(id),
    territory_id  BIGINT      NOT NULL,
    winner_id     BIGINT      NOT NULL,
    winner_name   VARCHAR(50),
    final_price   INTEGER     NOT NULL,
    won_at        TIMESTAMP   NOT NULL,
    season_id     BIGINT
);
