-- ranking-service 초기 스키마. season_territory_holds만 소유한다.
-- season·user·territory는 다른 서비스 소유라 FK 없이 식별자(bigint)만 보관한다.
-- 랭킹 ZSet(territory_hold·auction_spend)은 공유 Redis에 있어 여기 스키마엔 없다.
CREATE TABLE season_territory_holds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_id    BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    territory_id BIGINT       NOT NULL,
    grade        VARCHAR(1)   NOT NULL,
    held_from    TIMESTAMP    NOT NULL,
    held_until   TIMESTAMP
);

-- 시즌 집계(findAllBySeasonId)·내 등급 분포(findBySeasonIdAndUserId)·열린 점유 조회 최적화.
CREATE INDEX idx_hold_season ON season_territory_holds (season_id);
CREATE INDEX idx_hold_season_user ON season_territory_holds (season_id, user_id);
CREATE INDEX idx_hold_open ON season_territory_holds (season_id, user_id, territory_id)
    WHERE held_until IS NULL;
