--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_audit_logs (
    id bigint NOT NULL,
    action character varying(50) NOT NULL,
    admin_user_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    detail_json text,
    target_id bigint,
    target_type character varying(20)
);


--
-- Name: admin_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.admin_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_settings (
    id bigint NOT NULL,
    setting_key character varying(50) NOT NULL,
    setting_value character varying(255) NOT NULL
);


--
-- Name: admin_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_settings_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_settings_id_seq OWNED BY public.admin_settings.id;


--
-- Name: attack_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attack_tokens (
    user_id bigint NOT NULL,
    normal_count integer DEFAULT 0 NOT NULL,
    precision_count integer DEFAULT 0 NOT NULL
);


--
-- Name: auction_bids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auction_bids (
    id bigint NOT NULL,
    auction_id bigint,
    bidder_id bigint,
    price integer NOT NULL,
    bid_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: auction_bids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auction_bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auction_bids_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auction_bids_id_seq OWNED BY public.auction_bids.id;


--
-- Name: auction_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auction_histories (
    id bigint NOT NULL,
    auction_id bigint,
    territory_id bigint,
    winner_id bigint,
    final_price integer NOT NULL,
    won_at timestamp with time zone NOT NULL,
    season_id bigint
);


--
-- Name: auction_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auction_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auction_histories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auction_histories_id_seq OWNED BY public.auction_histories.id;


--
-- Name: auctions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auctions (
    id bigint NOT NULL,
    territory_id bigint,
    current_bidder_id bigint,
    current_price integer NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    max_extend_until timestamp with time zone NOT NULL,
    settled boolean NOT NULL
);


--
-- Name: auctions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.auctions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: auctions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.auctions_id_seq OWNED BY public.auctions.id;


--
-- Name: bonus_tiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bonus_tiles (
    id bigint NOT NULL,
    territory_id bigint,
    multiplier numeric(4,2) NOT NULL,
    description character varying(100)
);


--
-- Name: bonus_tiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.bonus_tiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: bonus_tiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.bonus_tiles_id_seq OWNED BY public.bonus_tiles.id;


--
-- Name: building_castle_limits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_castle_limits (
    id bigint NOT NULL,
    castle_level integer NOT NULL,
    max_count integer NOT NULL,
    building_type_id bigint NOT NULL
);


--
-- Name: building_castle_limits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.building_castle_limits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.building_castle_limits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: building_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_instances (
    id bigint NOT NULL,
    territory_id bigint,
    island_id bigint,
    building_type_id bigint NOT NULL,
    user_id bigint,
    pos_x integer NOT NULL,
    pos_y integer NOT NULL,
    hp integer NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    zone integer NOT NULL,
    is_destroyed boolean DEFAULT false NOT NULL,
    stored_gp integer DEFAULT 0 NOT NULL,
    workshop_debuff_until timestamp with time zone,
    build_complete_at timestamp(6) without time zone,
    upgrade_to_level integer,
    stored_food integer DEFAULT 0 NOT NULL,
    is_repairing boolean DEFAULT false NOT NULL
);


--
-- Name: building_instances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.building_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: building_instances_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.building_instances_id_seq OWNED BY public.building_instances.id;


--
-- Name: building_level_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_level_specs (
    id bigint NOT NULL,
    building_type_id bigint NOT NULL,
    level integer NOT NULL,
    upgrade_cost_gp integer,
    defense_power integer,
    food_production_rate integer,
    unit_capacity_per_level integer,
    gp_production_rate integer,
    max_hp integer,
    upgrade_time_seconds integer
);


--
-- Name: building_level_specs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.building_level_specs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: building_level_specs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.building_level_specs_id_seq OWNED BY public.building_level_specs.id;


--
-- Name: building_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.building_types (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    max_hp integer NOT NULL,
    base_cost_gp integer NOT NULL,
    zone_restriction integer,
    defense_power integer,
    food_production_rate integer,
    unit_capacity_per_level integer,
    gp_production_rate integer,
    icon character varying(10),
    color_hex character varying(7),
    display_name character varying(30),
    category character varying(20),
    upgrade_cost_gp integer,
    ap_cost integer,
    build_time_seconds integer,
    upgrade_time_seconds integer
);


--
-- Name: building_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.building_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: building_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.building_types_id_seq OWNED BY public.building_types.id;


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    room_id bigint,
    sender_id bigint,
    content text NOT NULL,
    sent_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_messages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_messages_id_seq OWNED BY public.chat_messages.id;


--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_rooms (
    id bigint NOT NULL,
    type character varying(10) NOT NULL,
    target_id bigint
);


--
-- Name: chat_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_rooms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_rooms_id_seq OWNED BY public.chat_rooms.id;


--
-- Name: color_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.color_histories (
    id bigint NOT NULL,
    territory_id bigint,
    user_id bigint,
    color_code character varying(7) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: color_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.color_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: color_histories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.color_histories_id_seq OWNED BY public.color_histories.id;


--
-- Name: continents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.continents (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    theme_color character varying(7) NOT NULL,
    description character varying(100),
    display_name character varying(50),
    grade character varying(2),
    min_trophy_required integer
);


--
-- Name: continents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.continents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: continents_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.continents_id_seq OWNED BY public.continents.id;


--
-- Name: global_vaults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.global_vaults (
    user_id bigint NOT NULL,
    stored_gp integer DEFAULT 0 NOT NULL,
    capacity integer DEFAULT 500 NOT NULL,
    last_transfer_at timestamp with time zone
);


--
-- Name: guild_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guild_members (
    id bigint NOT NULL,
    guild_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(10) DEFAULT 'MEMBER'::character varying NOT NULL,
    status character varying(10) DEFAULT 'PENDING'::character varying NOT NULL,
    message character varying(200),
    joined_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: guild_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.guild_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guild_members_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guild_members_id_seq OWNED BY public.guild_members.id;


--
-- Name: guilds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.guilds (
    id bigint NOT NULL,
    name character varying(20) NOT NULL,
    description character varying(200),
    emblem character varying(255),
    master_id bigint NOT NULL,
    max_members integer DEFAULT 30 NOT NULL,
    recruiting_status character varying(6) DEFAULT 'OPEN'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: guilds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.guilds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: guilds_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.guilds_id_seq OWNED BY public.guilds.id;


--
-- Name: home_islands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.home_islands (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    grid_size integer DEFAULT 10 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    grade character varying(5),
    last_harvest_at timestamp(6) without time zone,
    island_grade_id bigint,
    production_boost_until timestamp(6) without time zone
);


--
-- Name: home_islands_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.home_islands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: home_islands_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.home_islands_id_seq OWNED BY public.home_islands.id;


--
-- Name: interest_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.interest_groups (
    id bigint NOT NULL,
    user_id bigint,
    continent_id bigint
);


--
-- Name: interest_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.interest_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: interest_groups_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.interest_groups_id_seq OWNED BY public.interest_groups.id;


--
-- Name: island_grades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.island_grades (
    id bigint NOT NULL,
    castle_level_required integer NOT NULL,
    grid_size integer NOT NULL,
    name character varying(5) NOT NULL,
    zone1_radius integer NOT NULL,
    zone2_radius integer NOT NULL
);


--
-- Name: island_grades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.island_grades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.island_grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_purchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_purchases (
    id bigint NOT NULL,
    user_id bigint,
    item_id bigint,
    quantity integer DEFAULT 1 NOT NULL,
    target_territory_id bigint,
    purchased_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: item_purchases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.item_purchases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: item_purchases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.item_purchases_id_seq OWNED BY public.item_purchases.id;


--
-- Name: items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.items (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    item_type character varying(20) NOT NULL,
    description character varying(200),
    cost_ap integer,
    cost_gp integer,
    daily_limit integer,
    gp_reward integer,
    icon_url character varying(100)
);


--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.items_id_seq OWNED BY public.items.id;


--
-- Name: land_tax_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.land_tax_logs (
    id bigint NOT NULL,
    user_id bigint,
    territory_count integer NOT NULL,
    gp_charged integer NOT NULL,
    status character varying(10) NOT NULL,
    charged_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: land_tax_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.land_tax_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: land_tax_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.land_tax_logs_id_seq OWNED BY public.land_tax_logs.id;


--
-- Name: notification_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_logs (
    id bigint NOT NULL,
    user_id bigint,
    type character varying(20) NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notification_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notification_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notification_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notification_logs_id_seq OWNED BY public.notification_logs.id;


--
-- Name: notification_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_settings (
    user_id bigint NOT NULL,
    is_outbid_enabled boolean DEFAULT true,
    is_auction_start_enabled boolean DEFAULT true,
    is_marketing_enabled boolean DEFAULT false,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: season_missions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_missions (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    description character varying(200) NOT NULL,
    goal_count integer NOT NULL,
    period character varying(10) NOT NULL,
    sort_order integer NOT NULL,
    title character varying(100) NOT NULL,
    trigger_type character varying(20) NOT NULL,
    xp_reward integer NOT NULL,
    season_id bigint NOT NULL,
    CONSTRAINT season_missions_period_check CHECK (((period)::text = ANY ((ARRAY['DAILY'::character varying, 'WEEKLY'::character varying, 'SEASON'::character varying])::text[]))),
    CONSTRAINT season_missions_trigger_type_check CHECK (((trigger_type)::text = ANY ((ARRAY['ATTENDANCE'::character varying, 'AUCTION_WIN'::character varying, 'SIEGE_WIN'::character varying])::text[])))
);


--
-- Name: season_missions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.season_missions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.season_missions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: season_pass_level_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_pass_level_rewards (
    id bigint NOT NULL,
    season_id bigint NOT NULL,
    level integer NOT NULL,
    reward_name character varying(100) NOT NULL,
    track character varying(10) DEFAULT 'FREE'::character varying NOT NULL,
    reward_kind character varying(30) DEFAULT 'ITEM'::character varying NOT NULL,
    item_type character varying(20),
    quantity integer DEFAULT 1 NOT NULL
);


--
-- Name: season_pass_level_rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.season_pass_level_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: season_pass_level_rewards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.season_pass_level_rewards_id_seq OWNED BY public.season_pass_level_rewards.id;


--
-- Name: season_pass_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_pass_progress (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    season_id bigint NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    xp integer DEFAULT 0 NOT NULL
);


--
-- Name: season_pass_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.season_pass_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: season_pass_progress_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.season_pass_progress_id_seq OWNED BY public.season_pass_progress.id;


--
-- Name: season_pass_reward_claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_pass_reward_claims (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    reward_id bigint NOT NULL,
    claimed_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: season_pass_reward_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.season_pass_reward_claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: season_pass_reward_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.season_pass_reward_claims_id_seq OWNED BY public.season_pass_reward_claims.id;


--
-- Name: season_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_passes (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    cost_ap integer NOT NULL,
    duration_days integer DEFAULT 30 NOT NULL,
    island_bonus_pct integer NOT NULL,
    extra_builders integer DEFAULT 1 NOT NULL,
    tax_exempt_bonus integer DEFAULT 2 NOT NULL,
    build_time_reduction_pct integer DEFAULT 0 NOT NULL
);


--
-- Name: season_passes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.season_passes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: season_passes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.season_passes_id_seq OWNED BY public.season_passes.id;


--
-- Name: season_rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_rewards (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    season_id bigint NOT NULL,
    league character varying(10) NOT NULL,
    gp_reward integer NOT NULL,
    attack_token_normal integer DEFAULT 0 NOT NULL,
    attack_token_precision integer DEFAULT 0 NOT NULL,
    title_reward character varying(30),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: season_rewards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.season_rewards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: season_rewards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.season_rewards_id_seq OWNED BY public.season_rewards.id;


--
-- Name: season_territory_holds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.season_territory_holds (
    id bigint NOT NULL,
    grade character varying(1) NOT NULL,
    held_from timestamp(6) without time zone NOT NULL,
    held_until timestamp(6) without time zone,
    season_id bigint NOT NULL,
    territory_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: season_territory_holds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.season_territory_holds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.season_territory_holds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seasons; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seasons (
    id bigint NOT NULL,
    season_number integer NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone,
    processed_at timestamp with time zone
);


--
-- Name: seasons_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.seasons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: seasons_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.seasons_id_seq OWNED BY public.seasons.id;


--
-- Name: siege_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.siege_events (
    id bigint NOT NULL,
    attacker_id bigint NOT NULL,
    defender_id bigint NOT NULL,
    target_territory_id bigint NOT NULL,
    target_building_id bigint,
    attack_zone integer NOT NULL,
    status character varying(10) DEFAULT 'PENDING'::character varying NOT NULL,
    siege_start_at timestamp with time zone NOT NULL,
    resolve_at timestamp with time zone NOT NULL
);


--
-- Name: siege_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.siege_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: siege_events_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.siege_events_id_seq OWNED BY public.siege_events.id;


--
-- Name: siege_forces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.siege_forces (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    siege_id bigint NOT NULL,
    unit_type_id bigint NOT NULL,
    level integer NOT NULL
);


--
-- Name: siege_forces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.siege_forces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.siege_forces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: siege_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.siege_results (
    id bigint NOT NULL,
    siege_id bigint NOT NULL,
    is_attacker_win boolean NOT NULL,
    attacker_units_lost integer,
    defender_units_lost integer,
    looted_gp integer DEFAULT 0 NOT NULL,
    result_type character varying(15),
    applied_cooldown_hours integer
);


--
-- Name: siege_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.siege_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: siege_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.siege_results_id_seq OWNED BY public.siege_results.id;


--
-- Name: siege_structures; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.siege_structures (
    id bigint NOT NULL,
    coord_x integer NOT NULL,
    coord_y integer NOT NULL,
    type character varying(10) NOT NULL,
    siege_id bigint NOT NULL,
    CONSTRAINT siege_structures_type_check CHECK (((type)::text = ANY ((ARRAY['STAGING'::character varying, 'TOWER'::character varying, 'SUPPLY'::character varying])::text[])))
);


--
-- Name: siege_structures_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.siege_structures ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.siege_structures_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: territories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territories (
    id bigint NOT NULL,
    coord_x integer NOT NULL,
    coord_y integer NOT NULL,
    continent_id bigint,
    owner_id bigint,
    current_color character varying(7),
    occupied_until timestamp with time zone,
    status character varying(10) NOT NULL,
    base_production_rate integer DEFAULT 1 NOT NULL,
    last_produced_at timestamp with time zone,
    grade_id bigint,
    next_auction_at timestamp(6) without time zone,
    auction_enabled boolean DEFAULT true NOT NULL,
    protected_until timestamp(6) without time zone
);


--
-- Name: territories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.territories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: territories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.territories_id_seq OWNED BY public.territories.id;


--
-- Name: territory_grades; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territory_grades (
    id bigint NOT NULL,
    grade character varying(1) NOT NULL,
    production_multiplier numeric(3,1) NOT NULL,
    auction_price_multiplier numeric(3,1) NOT NULL,
    pre_built_count integer DEFAULT 0 NOT NULL,
    spawn_rate numeric(4,3) NOT NULL,
    grid_size integer NOT NULL,
    zone1_radius integer NOT NULL,
    zone2_radius integer NOT NULL
);


--
-- Name: territory_grades_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.territory_grades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: territory_grades_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.territory_grades_id_seq OWNED BY public.territory_grades.id;


--
-- Name: territory_production_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.territory_production_logs (
    id bigint NOT NULL,
    territory_id bigint,
    owner_id bigint,
    amount integer NOT NULL,
    reason character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: territory_production_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.territory_production_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: territory_production_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.territory_production_logs_id_seq OWNED BY public.territory_production_logs.id;


--
-- Name: trophy_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trophy_logs (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    season_id bigint NOT NULL,
    siege_id bigint,
    delta integer NOT NULL,
    reason character varying(30) NOT NULL,
    score_after integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: trophy_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.trophy_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: trophy_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.trophy_logs_id_seq OWNED BY public.trophy_logs.id;


--
-- Name: unit_instances; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_instances (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    unit_type_id bigint NOT NULL,
    quantity integer NOT NULL,
    deployed_territory_id bigint,
    home_island_id bigint,
    home_territory_id bigint,
    move_complete_at timestamp(6) without time zone,
    deployed_building_id bigint,
    level integer DEFAULT 1 NOT NULL,
    CONSTRAINT unit_instances_home_location_check CHECK ((((home_territory_id IS NOT NULL) AND (home_island_id IS NULL)) OR ((home_territory_id IS NULL) AND (home_island_id IS NOT NULL))))
);


--
-- Name: unit_instances_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.unit_instances_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: unit_instances_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.unit_instances_id_seq OWNED BY public.unit_instances.id;


--
-- Name: unit_research; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_research (
    id bigint NOT NULL,
    pending_level integer,
    research_complete_at timestamp(6) without time zone,
    researched_level integer NOT NULL,
    unit_type_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: unit_research_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit_research ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_research_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unit_type_level_specs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_type_level_specs (
    id bigint NOT NULL,
    attack_power integer NOT NULL,
    defense_power integer NOT NULL,
    level integer NOT NULL,
    required_barracks_level integer NOT NULL,
    train_cost_food integer NOT NULL,
    unit_type_id bigint NOT NULL
);


--
-- Name: unit_type_level_specs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.unit_type_level_specs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_type_level_specs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unit_types; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.unit_types (
    id bigint NOT NULL,
    name character varying(30) NOT NULL,
    attack_power integer NOT NULL,
    defense_power integer NOT NULL,
    cost_gp integer NOT NULL,
    food_cost integer NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    color_hex character varying(7),
    display_name character varying(30),
    icon character varying(10),
    building_damage integer DEFAULT 0 NOT NULL
);


--
-- Name: unit_types_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.unit_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: unit_types_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.unit_types_id_seq OWNED BY public.unit_types.id;


--
-- Name: user_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_items (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    item_id bigint NOT NULL,
    quantity integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_items_id_seq OWNED BY public.user_items.id;


--
-- Name: user_mission_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_mission_progress (
    id bigint NOT NULL,
    claimed boolean NOT NULL,
    completed_count integer NOT NULL,
    period_started_at timestamp(6) without time zone NOT NULL,
    mission_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_mission_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_mission_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_mission_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    user_id bigint NOT NULL,
    profile_image_url character varying(255),
    updated_at timestamp(6) without time zone NOT NULL
);


--
-- Name: user_season_passes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_season_passes (
    id bigint NOT NULL,
    user_id bigint,
    season_pass_id bigint,
    started_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    bonus_build_time_reduction_pct integer DEFAULT 0 NOT NULL
);


--
-- Name: user_season_passes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_season_passes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_season_passes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_season_passes_id_seq OWNED BY public.user_season_passes.id;


--
-- Name: user_trophies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_trophies (
    user_id bigint NOT NULL,
    score integer DEFAULT 0 NOT NULL,
    league character varying(10) DEFAULT 'BRONZE'::character varying NOT NULL,
    season_id bigint NOT NULL,
    last_reset_season_id bigint,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash text NOT NULL,
    nickname character varying(30) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    status character varying(10) DEFAULT 'ACTIVE'::character varying NOT NULL,
    totp_secret character varying(64),
    role character varying(10) DEFAULT 'USER'::character varying NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: wallets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallets (
    user_id bigint NOT NULL,
    available_ap integer DEFAULT 0 NOT NULL,
    locked_ap integer DEFAULT 0 NOT NULL,
    available_gp integer DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    available_food integer DEFAULT 100 NOT NULL
);


--
-- Name: wishlists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wishlists (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    territory_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: wishlists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wishlists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_settings id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_settings ALTER COLUMN id SET DEFAULT nextval('public.admin_settings_id_seq'::regclass);


--
-- Name: auction_bids id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_bids ALTER COLUMN id SET DEFAULT nextval('public.auction_bids_id_seq'::regclass);


--
-- Name: auction_histories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories ALTER COLUMN id SET DEFAULT nextval('public.auction_histories_id_seq'::regclass);


--
-- Name: auctions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions ALTER COLUMN id SET DEFAULT nextval('public.auctions_id_seq'::regclass);


--
-- Name: bonus_tiles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_tiles ALTER COLUMN id SET DEFAULT nextval('public.bonus_tiles_id_seq'::regclass);


--
-- Name: building_instances id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances ALTER COLUMN id SET DEFAULT nextval('public.building_instances_id_seq'::regclass);


--
-- Name: building_level_specs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_level_specs ALTER COLUMN id SET DEFAULT nextval('public.building_level_specs_id_seq'::regclass);


--
-- Name: building_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_types ALTER COLUMN id SET DEFAULT nextval('public.building_types_id_seq'::regclass);


--
-- Name: chat_messages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages ALTER COLUMN id SET DEFAULT nextval('public.chat_messages_id_seq'::regclass);


--
-- Name: chat_rooms id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms ALTER COLUMN id SET DEFAULT nextval('public.chat_rooms_id_seq'::regclass);


--
-- Name: color_histories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_histories ALTER COLUMN id SET DEFAULT nextval('public.color_histories_id_seq'::regclass);


--
-- Name: continents id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.continents ALTER COLUMN id SET DEFAULT nextval('public.continents_id_seq'::regclass);


--
-- Name: guild_members id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_members ALTER COLUMN id SET DEFAULT nextval('public.guild_members_id_seq'::regclass);


--
-- Name: guilds id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guilds ALTER COLUMN id SET DEFAULT nextval('public.guilds_id_seq'::regclass);


--
-- Name: home_islands id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_islands ALTER COLUMN id SET DEFAULT nextval('public.home_islands_id_seq'::regclass);


--
-- Name: interest_groups id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_groups ALTER COLUMN id SET DEFAULT nextval('public.interest_groups_id_seq'::regclass);


--
-- Name: item_purchases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_purchases ALTER COLUMN id SET DEFAULT nextval('public.item_purchases_id_seq'::regclass);


--
-- Name: items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items ALTER COLUMN id SET DEFAULT nextval('public.items_id_seq'::regclass);


--
-- Name: land_tax_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.land_tax_logs ALTER COLUMN id SET DEFAULT nextval('public.land_tax_logs_id_seq'::regclass);


--
-- Name: notification_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs ALTER COLUMN id SET DEFAULT nextval('public.notification_logs_id_seq'::regclass);


--
-- Name: season_pass_level_rewards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_level_rewards ALTER COLUMN id SET DEFAULT nextval('public.season_pass_level_rewards_id_seq'::regclass);


--
-- Name: season_pass_progress id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress ALTER COLUMN id SET DEFAULT nextval('public.season_pass_progress_id_seq'::regclass);


--
-- Name: season_pass_reward_claims id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_reward_claims ALTER COLUMN id SET DEFAULT nextval('public.season_pass_reward_claims_id_seq'::regclass);


--
-- Name: season_passes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_passes ALTER COLUMN id SET DEFAULT nextval('public.season_passes_id_seq'::regclass);


--
-- Name: season_rewards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_rewards ALTER COLUMN id SET DEFAULT nextval('public.season_rewards_id_seq'::regclass);


--
-- Name: seasons id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons ALTER COLUMN id SET DEFAULT nextval('public.seasons_id_seq'::regclass);


--
-- Name: siege_events id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events ALTER COLUMN id SET DEFAULT nextval('public.siege_events_id_seq'::regclass);


--
-- Name: siege_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_results ALTER COLUMN id SET DEFAULT nextval('public.siege_results_id_seq'::regclass);


--
-- Name: territories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territories ALTER COLUMN id SET DEFAULT nextval('public.territories_id_seq'::regclass);


--
-- Name: territory_grades id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_grades ALTER COLUMN id SET DEFAULT nextval('public.territory_grades_id_seq'::regclass);


--
-- Name: territory_production_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_production_logs ALTER COLUMN id SET DEFAULT nextval('public.territory_production_logs_id_seq'::regclass);


--
-- Name: trophy_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy_logs ALTER COLUMN id SET DEFAULT nextval('public.trophy_logs_id_seq'::regclass);


--
-- Name: unit_instances id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances ALTER COLUMN id SET DEFAULT nextval('public.unit_instances_id_seq'::regclass);


--
-- Name: unit_types id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_types ALTER COLUMN id SET DEFAULT nextval('public.unit_types_id_seq'::regclass);


--
-- Name: user_items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items ALTER COLUMN id SET DEFAULT nextval('public.user_items_id_seq'::regclass);


--
-- Name: user_season_passes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_season_passes ALTER COLUMN id SET DEFAULT nextval('public.user_season_passes_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: admin_audit_logs admin_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: admin_settings admin_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_settings
    ADD CONSTRAINT admin_settings_pkey PRIMARY KEY (id);


--
-- Name: admin_settings admin_settings_setting_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_settings
    ADD CONSTRAINT admin_settings_setting_key_key UNIQUE (setting_key);


--
-- Name: attack_tokens attack_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attack_tokens
    ADD CONSTRAINT attack_tokens_pkey PRIMARY KEY (user_id);


--
-- Name: auction_bids auction_bids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_bids
    ADD CONSTRAINT auction_bids_pkey PRIMARY KEY (id);


--
-- Name: auction_histories auction_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories
    ADD CONSTRAINT auction_histories_pkey PRIMARY KEY (id);


--
-- Name: auctions auctions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT auctions_pkey PRIMARY KEY (id);


--
-- Name: bonus_tiles bonus_tiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_tiles
    ADD CONSTRAINT bonus_tiles_pkey PRIMARY KEY (id);


--
-- Name: bonus_tiles bonus_tiles_territory_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_tiles
    ADD CONSTRAINT bonus_tiles_territory_id_key UNIQUE (territory_id);


--
-- Name: building_castle_limits building_castle_limits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_castle_limits
    ADD CONSTRAINT building_castle_limits_pkey PRIMARY KEY (id);


--
-- Name: building_instances building_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances
    ADD CONSTRAINT building_instances_pkey PRIMARY KEY (id);


--
-- Name: building_level_specs building_level_specs_building_type_id_level_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_level_specs
    ADD CONSTRAINT building_level_specs_building_type_id_level_key UNIQUE (building_type_id, level);


--
-- Name: building_level_specs building_level_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_level_specs
    ADD CONSTRAINT building_level_specs_pkey PRIMARY KEY (id);


--
-- Name: building_types building_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_types
    ADD CONSTRAINT building_types_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);


--
-- Name: color_histories color_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_histories
    ADD CONSTRAINT color_histories_pkey PRIMARY KEY (id);


--
-- Name: continents continents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.continents
    ADD CONSTRAINT continents_pkey PRIMARY KEY (id);


--
-- Name: global_vaults global_vaults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_vaults
    ADD CONSTRAINT global_vaults_pkey PRIMARY KEY (user_id);


--
-- Name: guild_members guild_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_members
    ADD CONSTRAINT guild_members_pkey PRIMARY KEY (id);


--
-- Name: guilds guilds_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guilds
    ADD CONSTRAINT guilds_name_key UNIQUE (name);


--
-- Name: guilds guilds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guilds
    ADD CONSTRAINT guilds_pkey PRIMARY KEY (id);


--
-- Name: home_islands home_islands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_islands
    ADD CONSTRAINT home_islands_pkey PRIMARY KEY (id);


--
-- Name: home_islands home_islands_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_islands
    ADD CONSTRAINT home_islands_user_id_key UNIQUE (user_id);


--
-- Name: interest_groups interest_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_groups
    ADD CONSTRAINT interest_groups_pkey PRIMARY KEY (id);


--
-- Name: island_grades island_grades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.island_grades
    ADD CONSTRAINT island_grades_pkey PRIMARY KEY (id);


--
-- Name: item_purchases item_purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_purchases
    ADD CONSTRAINT item_purchases_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: land_tax_logs land_tax_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.land_tax_logs
    ADD CONSTRAINT land_tax_logs_pkey PRIMARY KEY (id);


--
-- Name: notification_logs notification_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs
    ADD CONSTRAINT notification_logs_pkey PRIMARY KEY (id);


--
-- Name: notification_settings notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_pkey PRIMARY KEY (user_id);


--
-- Name: season_missions season_missions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_missions
    ADD CONSTRAINT season_missions_pkey PRIMARY KEY (id);


--
-- Name: season_pass_level_rewards season_pass_level_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_level_rewards
    ADD CONSTRAINT season_pass_level_rewards_pkey PRIMARY KEY (id);


--
-- Name: season_pass_progress season_pass_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress
    ADD CONSTRAINT season_pass_progress_pkey PRIMARY KEY (id);


--
-- Name: season_pass_progress season_pass_progress_user_id_season_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress
    ADD CONSTRAINT season_pass_progress_user_id_season_id_key UNIQUE (user_id, season_id);


--
-- Name: season_pass_reward_claims season_pass_reward_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_reward_claims
    ADD CONSTRAINT season_pass_reward_claims_pkey PRIMARY KEY (id);


--
-- Name: season_passes season_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_passes
    ADD CONSTRAINT season_passes_pkey PRIMARY KEY (id);


--
-- Name: season_rewards season_rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_rewards
    ADD CONSTRAINT season_rewards_pkey PRIMARY KEY (id);


--
-- Name: season_territory_holds season_territory_holds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_territory_holds
    ADD CONSTRAINT season_territory_holds_pkey PRIMARY KEY (id);


--
-- Name: seasons seasons_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT seasons_pkey PRIMARY KEY (id);


--
-- Name: seasons seasons_season_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seasons
    ADD CONSTRAINT seasons_season_number_key UNIQUE (season_number);


--
-- Name: siege_events siege_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events
    ADD CONSTRAINT siege_events_pkey PRIMARY KEY (id);


--
-- Name: siege_forces siege_forces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_forces
    ADD CONSTRAINT siege_forces_pkey PRIMARY KEY (id);


--
-- Name: siege_results siege_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_results
    ADD CONSTRAINT siege_results_pkey PRIMARY KEY (id);


--
-- Name: siege_results siege_results_siege_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_results
    ADD CONSTRAINT siege_results_siege_id_key UNIQUE (siege_id);


--
-- Name: siege_structures siege_structures_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_structures
    ADD CONSTRAINT siege_structures_pkey PRIMARY KEY (id);


--
-- Name: territories territories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territories
    ADD CONSTRAINT territories_pkey PRIMARY KEY (id);


--
-- Name: territory_grades territory_grades_grade_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_grades
    ADD CONSTRAINT territory_grades_grade_key UNIQUE (grade);


--
-- Name: territory_grades territory_grades_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_grades
    ADD CONSTRAINT territory_grades_pkey PRIMARY KEY (id);


--
-- Name: territory_production_logs territory_production_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_production_logs
    ADD CONSTRAINT territory_production_logs_pkey PRIMARY KEY (id);


--
-- Name: trophy_logs trophy_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy_logs
    ADD CONSTRAINT trophy_logs_pkey PRIMARY KEY (id);


--
-- Name: wishlists uk2f1vy8ls4uya5sihkw4t6bykv; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT uk2f1vy8ls4uya5sihkw4t6bykv UNIQUE (user_id, territory_id);


--
-- Name: island_grades ukaawe5sdccwwlxhqcxsfk3g0hl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.island_grades
    ADD CONSTRAINT ukaawe5sdccwwlxhqcxsfk3g0hl UNIQUE (name);


--
-- Name: building_level_specs ukk2jdv858yfi5d781ejer7pbh7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_level_specs
    ADD CONSTRAINT ukk2jdv858yfi5d781ejer7pbh7 UNIQUE (building_type_id, level);


--
-- Name: user_mission_progress ukoomrudej1p5tlllhjerkobl7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_mission_progress
    ADD CONSTRAINT ukoomrudej1p5tlllhjerkobl7 UNIQUE (user_id, mission_id);


--
-- Name: unit_type_level_specs ukoruv4tngjdln6biic0ke2vcwh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_level_specs
    ADD CONSTRAINT ukoruv4tngjdln6biic0ke2vcwh UNIQUE (unit_type_id, level);


--
-- Name: building_castle_limits ukq4edsr8wa3uycvl0dsb9qef27; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_castle_limits
    ADD CONSTRAINT ukq4edsr8wa3uycvl0dsb9qef27 UNIQUE (building_type_id, castle_level);


--
-- Name: season_pass_progress uksjiw8h12pfdpgg5l4urabuj3d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress
    ADD CONSTRAINT uksjiw8h12pfdpgg5l4urabuj3d UNIQUE (user_id, season_id);


--
-- Name: user_items ukt1fm75442g6mqcekt9ojereou; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items
    ADD CONSTRAINT ukt1fm75442g6mqcekt9ojereou UNIQUE (user_id, item_id);


--
-- Name: unit_research ukt6n2b0gkxpepehbtogds0ttrw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_research
    ADD CONSTRAINT ukt6n2b0gkxpepehbtogds0ttrw UNIQUE (user_id, unit_type_id);


--
-- Name: unit_instances unit_instances_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT unit_instances_pkey PRIMARY KEY (id);


--
-- Name: unit_research unit_research_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_research
    ADD CONSTRAINT unit_research_pkey PRIMARY KEY (id);


--
-- Name: unit_type_level_specs unit_type_level_specs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_level_specs
    ADD CONSTRAINT unit_type_level_specs_pkey PRIMARY KEY (id);


--
-- Name: unit_types unit_types_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_types
    ADD CONSTRAINT unit_types_pkey PRIMARY KEY (id);


--
-- Name: user_items user_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items
    ADD CONSTRAINT user_items_pkey PRIMARY KEY (id);


--
-- Name: user_items user_items_user_id_item_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items
    ADD CONSTRAINT user_items_user_id_item_id_key UNIQUE (user_id, item_id);


--
-- Name: user_mission_progress user_mission_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_mission_progress
    ADD CONSTRAINT user_mission_progress_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id);


--
-- Name: user_season_passes user_season_passes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_season_passes
    ADD CONSTRAINT user_season_passes_pkey PRIMARY KEY (id);


--
-- Name: user_trophies user_trophies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trophies
    ADD CONSTRAINT user_trophies_pkey PRIMARY KEY (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_nickname_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_nickname_key UNIQUE (nickname);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: wallets wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_pkey PRIMARY KEY (user_id);


--
-- Name: wishlists wishlists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT wishlists_pkey PRIMARY KEY (id);


--
-- Name: idx_auction_bids_auction_bid_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auction_bids_auction_bid_at ON public.auction_bids USING btree (auction_id, bid_at);


--
-- Name: attack_tokens attack_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attack_tokens
    ADD CONSTRAINT attack_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: auction_bids auction_bids_auction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_bids
    ADD CONSTRAINT auction_bids_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: auction_bids auction_bids_bidder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_bids
    ADD CONSTRAINT auction_bids_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES public.users(id);


--
-- Name: auction_histories auction_histories_auction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories
    ADD CONSTRAINT auction_histories_auction_id_fkey FOREIGN KEY (auction_id) REFERENCES public.auctions(id);


--
-- Name: auction_histories auction_histories_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories
    ADD CONSTRAINT auction_histories_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: auction_histories auction_histories_winner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories
    ADD CONSTRAINT auction_histories_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.users(id);


--
-- Name: auctions auctions_current_bidder_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT auctions_current_bidder_id_fkey FOREIGN KEY (current_bidder_id) REFERENCES public.users(id);


--
-- Name: auctions auctions_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auctions
    ADD CONSTRAINT auctions_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: bonus_tiles bonus_tiles_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bonus_tiles
    ADD CONSTRAINT bonus_tiles_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: building_instances building_instances_building_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances
    ADD CONSTRAINT building_instances_building_type_id_fkey FOREIGN KEY (building_type_id) REFERENCES public.building_types(id);


--
-- Name: building_instances building_instances_island_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances
    ADD CONSTRAINT building_instances_island_id_fkey FOREIGN KEY (island_id) REFERENCES public.home_islands(id);


--
-- Name: building_instances building_instances_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances
    ADD CONSTRAINT building_instances_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: building_instances building_instances_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_instances
    ADD CONSTRAINT building_instances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: building_level_specs building_level_specs_building_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_level_specs
    ADD CONSTRAINT building_level_specs_building_type_id_fkey FOREIGN KEY (building_type_id) REFERENCES public.building_types(id);


--
-- Name: chat_messages chat_messages_room_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_room_id_fkey FOREIGN KEY (room_id) REFERENCES public.chat_rooms(id);


--
-- Name: chat_messages chat_messages_sender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id);


--
-- Name: color_histories color_histories_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_histories
    ADD CONSTRAINT color_histories_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: color_histories color_histories_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.color_histories
    ADD CONSTRAINT color_histories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: wishlists fk330pyw2el06fn5g28ypyljt16; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fk330pyw2el06fn5g28ypyljt16 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: siege_forces fk4s3w1b010263y8d774nh4djh9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_forces
    ADD CONSTRAINT fk4s3w1b010263y8d774nh4djh9 FOREIGN KEY (unit_type_id) REFERENCES public.unit_types(id);


--
-- Name: unit_instances fk5puf1ru8c66pd0p7x86sp8hjf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT fk5puf1ru8c66pd0p7x86sp8hjf FOREIGN KEY (home_island_id) REFERENCES public.home_islands(id);


--
-- Name: unit_research fk7wo00r3ytqwhapsxcyihfkkwt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_research
    ADD CONSTRAINT fk7wo00r3ytqwhapsxcyihfkkwt FOREIGN KEY (unit_type_id) REFERENCES public.unit_types(id);


--
-- Name: siege_structures fk94ohmyh6sxq761wd5k127fdt5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_structures
    ADD CONSTRAINT fk94ohmyh6sxq761wd5k127fdt5 FOREIGN KEY (siege_id) REFERENCES public.siege_events(id);


--
-- Name: season_missions fk9kce81c3lfs9wtdot9gcuo558; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_missions
    ADD CONSTRAINT fk9kce81c3lfs9wtdot9gcuo558 FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: unit_instances fk9ngfas9fb7lkto5nkhver2hm5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT fk9ngfas9fb7lkto5nkhver2hm5 FOREIGN KEY (deployed_building_id) REFERENCES public.building_instances(id);


--
-- Name: home_islands fkaql6fho37ce3i6bdhsmso1gtf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_islands
    ADD CONSTRAINT fkaql6fho37ce3i6bdhsmso1gtf FOREIGN KEY (island_grade_id) REFERENCES public.island_grades(id);


--
-- Name: season_territory_holds fkbmerbpxmvx5c5l17ma8tjj7a4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_territory_holds
    ADD CONSTRAINT fkbmerbpxmvx5c5l17ma8tjj7a4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: season_territory_holds fkewy9ccwq8pew7xyx8wyl7nivg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_territory_holds
    ADD CONSTRAINT fkewy9ccwq8pew7xyx8wyl7nivg FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: building_castle_limits fkfpcftw8k4jxq2lk6aqvck0si6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.building_castle_limits
    ADD CONSTRAINT fkfpcftw8k4jxq2lk6aqvck0si6 FOREIGN KEY (building_type_id) REFERENCES public.building_types(id);


--
-- Name: unit_instances fki2qj9hbjrwn11l81x36l47rfy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT fki2qj9hbjrwn11l81x36l47rfy FOREIGN KEY (home_territory_id) REFERENCES public.territories(id);


--
-- Name: unit_research fkia7ecf27i6bp6c7yljkngw7gs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_research
    ADD CONSTRAINT fkia7ecf27i6bp6c7yljkngw7gs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_profiles fkjcad5nfve11khsnpwj1mv8frj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT fkjcad5nfve11khsnpwj1mv8frj FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: siege_forces fkjw9vy3n0sc8sv36tqu8fm5yi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_forces
    ADD CONSTRAINT fkjw9vy3n0sc8sv36tqu8fm5yi FOREIGN KEY (siege_id) REFERENCES public.siege_events(id);


--
-- Name: user_mission_progress fklaerryxso6w1o515g432xbpbx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_mission_progress
    ADD CONSTRAINT fklaerryxso6w1o515g432xbpbx FOREIGN KEY (mission_id) REFERENCES public.season_missions(id);


--
-- Name: user_mission_progress fklfppgkdbj5uufu8cdllq7nbmf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_mission_progress
    ADD CONSTRAINT fklfppgkdbj5uufu8cdllq7nbmf FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: unit_type_level_specs fklldiwfvhlx2gagrxetvt2cufa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_type_level_specs
    ADD CONSTRAINT fklldiwfvhlx2gagrxetvt2cufa FOREIGN KEY (unit_type_id) REFERENCES public.unit_types(id);


--
-- Name: wishlists fkmp9m2nfw2iq8xxqvj3t9b2khf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wishlists
    ADD CONSTRAINT fkmp9m2nfw2iq8xxqvj3t9b2khf FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: season_territory_holds fks6d48k463lo51ch5cjy7ttdw0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_territory_holds
    ADD CONSTRAINT fks6d48k463lo51ch5cjy7ttdw0 FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: auction_histories fkt77amjbqqfcbp9wty68x5py71; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auction_histories
    ADD CONSTRAINT fkt77amjbqqfcbp9wty68x5py71 FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: global_vaults global_vaults_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_vaults
    ADD CONSTRAINT global_vaults_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: guild_members guild_members_guild_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_members
    ADD CONSTRAINT guild_members_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES public.guilds(id);


--
-- Name: guild_members guild_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guild_members
    ADD CONSTRAINT guild_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: guilds guilds_master_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.guilds
    ADD CONSTRAINT guilds_master_id_fkey FOREIGN KEY (master_id) REFERENCES public.users(id);


--
-- Name: home_islands home_islands_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.home_islands
    ADD CONSTRAINT home_islands_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: interest_groups interest_groups_continent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_groups
    ADD CONSTRAINT interest_groups_continent_id_fkey FOREIGN KEY (continent_id) REFERENCES public.continents(id);


--
-- Name: interest_groups interest_groups_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.interest_groups
    ADD CONSTRAINT interest_groups_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: item_purchases item_purchases_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_purchases
    ADD CONSTRAINT item_purchases_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: item_purchases item_purchases_target_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_purchases
    ADD CONSTRAINT item_purchases_target_territory_id_fkey FOREIGN KEY (target_territory_id) REFERENCES public.territories(id);


--
-- Name: item_purchases item_purchases_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_purchases
    ADD CONSTRAINT item_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: land_tax_logs land_tax_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.land_tax_logs
    ADD CONSTRAINT land_tax_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notification_logs notification_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_logs
    ADD CONSTRAINT notification_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notification_settings notification_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_settings
    ADD CONSTRAINT notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: season_pass_level_rewards season_pass_level_rewards_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_level_rewards
    ADD CONSTRAINT season_pass_level_rewards_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: season_pass_progress season_pass_progress_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress
    ADD CONSTRAINT season_pass_progress_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: season_pass_progress season_pass_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_progress
    ADD CONSTRAINT season_pass_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: season_pass_reward_claims season_pass_reward_claims_reward_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_reward_claims
    ADD CONSTRAINT season_pass_reward_claims_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.season_pass_level_rewards(id);


--
-- Name: season_pass_reward_claims season_pass_reward_claims_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_pass_reward_claims
    ADD CONSTRAINT season_pass_reward_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: season_rewards season_rewards_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_rewards
    ADD CONSTRAINT season_rewards_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: season_rewards season_rewards_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.season_rewards
    ADD CONSTRAINT season_rewards_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: siege_events siege_events_attacker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events
    ADD CONSTRAINT siege_events_attacker_id_fkey FOREIGN KEY (attacker_id) REFERENCES public.users(id);


--
-- Name: siege_events siege_events_defender_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events
    ADD CONSTRAINT siege_events_defender_id_fkey FOREIGN KEY (defender_id) REFERENCES public.users(id);


--
-- Name: siege_events siege_events_target_building_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events
    ADD CONSTRAINT siege_events_target_building_id_fkey FOREIGN KEY (target_building_id) REFERENCES public.building_instances(id);


--
-- Name: siege_events siege_events_target_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_events
    ADD CONSTRAINT siege_events_target_territory_id_fkey FOREIGN KEY (target_territory_id) REFERENCES public.territories(id);


--
-- Name: siege_results siege_results_siege_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.siege_results
    ADD CONSTRAINT siege_results_siege_id_fkey FOREIGN KEY (siege_id) REFERENCES public.siege_events(id);


--
-- Name: territories territories_continent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territories
    ADD CONSTRAINT territories_continent_id_fkey FOREIGN KEY (continent_id) REFERENCES public.continents(id);


--
-- Name: territories territories_grade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territories
    ADD CONSTRAINT territories_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES public.territory_grades(id);


--
-- Name: territories territories_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territories
    ADD CONSTRAINT territories_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: territory_production_logs territory_production_logs_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_production_logs
    ADD CONSTRAINT territory_production_logs_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: territory_production_logs territory_production_logs_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.territory_production_logs
    ADD CONSTRAINT territory_production_logs_territory_id_fkey FOREIGN KEY (territory_id) REFERENCES public.territories(id);


--
-- Name: trophy_logs trophy_logs_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy_logs
    ADD CONSTRAINT trophy_logs_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: trophy_logs trophy_logs_siege_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy_logs
    ADD CONSTRAINT trophy_logs_siege_id_fkey FOREIGN KEY (siege_id) REFERENCES public.siege_events(id);


--
-- Name: trophy_logs trophy_logs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trophy_logs
    ADD CONSTRAINT trophy_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: unit_instances unit_instances_deployed_territory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT unit_instances_deployed_territory_id_fkey FOREIGN KEY (deployed_territory_id) REFERENCES public.territories(id);


--
-- Name: unit_instances unit_instances_unit_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT unit_instances_unit_type_id_fkey FOREIGN KEY (unit_type_id) REFERENCES public.unit_types(id);


--
-- Name: unit_instances unit_instances_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.unit_instances
    ADD CONSTRAINT unit_instances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_items user_items_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items
    ADD CONSTRAINT user_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id);


--
-- Name: user_items user_items_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_items
    ADD CONSTRAINT user_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_season_passes user_season_passes_season_pass_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_season_passes
    ADD CONSTRAINT user_season_passes_season_pass_id_fkey FOREIGN KEY (season_pass_id) REFERENCES public.season_passes(id);


--
-- Name: user_season_passes user_season_passes_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_season_passes
    ADD CONSTRAINT user_season_passes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_trophies user_trophies_last_reset_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trophies
    ADD CONSTRAINT user_trophies_last_reset_season_id_fkey FOREIGN KEY (last_reset_season_id) REFERENCES public.seasons(id);


--
-- Name: user_trophies user_trophies_season_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trophies
    ADD CONSTRAINT user_trophies_season_id_fkey FOREIGN KEY (season_id) REFERENCES public.seasons(id);


--
-- Name: user_trophies user_trophies_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_trophies
    ADD CONSTRAINT user_trophies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: wallets wallets_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallets
    ADD CONSTRAINT wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--
