-- combat-service owns building, island resources, military and siege state.
-- User and Territory references are scalar IDs only: no cross-service foreign keys.

CREATE TABLE island_grades (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(5)  NOT NULL UNIQUE,
    castle_level_required  INTEGER     NOT NULL,
    grid_size              INTEGER     NOT NULL,
    zone1_radius           INTEGER     NOT NULL,
    zone2_radius           INTEGER     NOT NULL
);

CREATE TABLE home_islands (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT      NOT NULL UNIQUE,
    island_grade_id         BIGINT      REFERENCES island_grades(id),
    level                   INTEGER     NOT NULL DEFAULT 1,
    grid_size               INTEGER     NOT NULL DEFAULT 10,
    grade                   VARCHAR(5),
    last_harvest_at         TIMESTAMP,
    production_boost_until  TIMESTAMP,
    created_at              TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE global_vaults (
    user_id           BIGINT      PRIMARY KEY,
    stored_gp         INTEGER     NOT NULL DEFAULT 0,
    capacity          INTEGER     NOT NULL DEFAULT 500,
    last_transfer_at  TIMESTAMP,
    CONSTRAINT chk_global_vault_gp_nonnegative CHECK (stored_gp >= 0),
    CONSTRAINT chk_global_vault_capacity_nonnegative CHECK (capacity >= 0)
);

CREATE TABLE building_types (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     VARCHAR(30)  NOT NULL UNIQUE,
    display_name             VARCHAR(30),
    category                 VARCHAR(20),
    width                    INTEGER      NOT NULL,
    height                   INTEGER      NOT NULL,
    max_hp                   INTEGER      NOT NULL,
    base_cost_gp             INTEGER      NOT NULL,
    upgrade_cost_gp          INTEGER,
    ap_cost                  INTEGER,
    zone_restriction         INTEGER,
    defense_power            INTEGER,
    food_production_rate     INTEGER,
    unit_capacity_per_level  INTEGER,
    gp_production_rate       INTEGER,
    build_time_seconds       INTEGER,
    upgrade_time_seconds     INTEGER,
    icon                     VARCHAR(10),
    color_hex                VARCHAR(7)
);

CREATE TABLE building_level_specs (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_type_id         BIGINT   NOT NULL REFERENCES building_types(id),
    level                    INTEGER  NOT NULL,
    upgrade_cost_gp          INTEGER,
    max_hp                   INTEGER,
    defense_power            INTEGER,
    food_production_rate     INTEGER,
    unit_capacity_per_level  INTEGER,
    gp_production_rate       INTEGER,
    upgrade_time_seconds     INTEGER,
    CONSTRAINT uk_building_level_spec UNIQUE (building_type_id, level)
);

CREATE TABLE building_castle_limits (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_type_id  BIGINT   NOT NULL REFERENCES building_types(id),
    castle_level      INTEGER  NOT NULL,
    max_count         INTEGER  NOT NULL,
    CONSTRAINT uk_building_castle_limit UNIQUE (building_type_id, castle_level)
);

CREATE TABLE building_instances (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_id             BIGINT,
    island_id                BIGINT REFERENCES home_islands(id),
    building_type_id         BIGINT      NOT NULL REFERENCES building_types(id),
    user_id                  BIGINT,
    pos_x                    INTEGER     NOT NULL,
    pos_y                    INTEGER     NOT NULL,
    hp                       INTEGER     NOT NULL,
    level                    INTEGER     NOT NULL DEFAULT 1,
    zone                     INTEGER     NOT NULL,
    is_destroyed             BOOLEAN     NOT NULL DEFAULT FALSE,
    stored_gp                INTEGER     NOT NULL DEFAULT 0,
    stored_food              INTEGER     NOT NULL DEFAULT 0,
    workshop_debuff_until    TIMESTAMP,
    build_complete_at        TIMESTAMP,
    upgrade_to_level         INTEGER,
    is_repairing             BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_building_location CHECK (num_nonnulls(territory_id, island_id, user_id) = 1),
    CONSTRAINT chk_building_stored_gp_nonnegative CHECK (stored_gp >= 0),
    CONSTRAINT chk_building_stored_food_nonnegative CHECK (stored_food >= 0)
);

CREATE INDEX idx_building_instances_territory ON building_instances (territory_id);
CREATE INDEX idx_building_instances_island ON building_instances (island_id);
CREATE INDEX idx_building_instances_inventory ON building_instances (user_id)
    WHERE user_id IS NOT NULL;

CREATE TABLE unit_types (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(30)  NOT NULL UNIQUE,
    display_name     VARCHAR(30),
    icon             VARCHAR(10),
    color_hex        VARCHAR(7),
    attack_power     INTEGER      NOT NULL,
    defense_power    INTEGER      NOT NULL,
    cost_gp          INTEGER      NOT NULL,
    food_cost        INTEGER      NOT NULL,
    building_damage  INTEGER      NOT NULL DEFAULT 0,
    level            INTEGER      NOT NULL DEFAULT 1
);

CREATE TABLE unit_type_level_specs (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_type_id             BIGINT   NOT NULL REFERENCES unit_types(id),
    level                    INTEGER  NOT NULL,
    attack_power             INTEGER  NOT NULL,
    defense_power            INTEGER  NOT NULL,
    train_cost_food          INTEGER  NOT NULL,
    required_barracks_level  INTEGER  NOT NULL,
    CONSTRAINT uk_unit_type_level_spec UNIQUE (unit_type_id, level)
);

CREATE TABLE unit_instances (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT      NOT NULL,
    unit_type_id           BIGINT      NOT NULL REFERENCES unit_types(id),
    quantity               INTEGER     NOT NULL,
    level                  INTEGER     NOT NULL DEFAULT 1,
    home_territory_id      BIGINT,
    home_island_id         BIGINT REFERENCES home_islands(id),
    deployed_territory_id  BIGINT,
    deployed_building_id   BIGINT REFERENCES building_instances(id),
    move_complete_at       TIMESTAMP,
    CONSTRAINT chk_unit_home_location CHECK (
        (home_territory_id IS NOT NULL AND home_island_id IS NULL)
        OR (home_territory_id IS NULL AND home_island_id IS NOT NULL)
    ),
    CONSTRAINT chk_unit_quantity_nonnegative CHECK (quantity >= 0)
);

CREATE INDEX idx_unit_instances_user ON unit_instances (user_id);
CREATE INDEX idx_unit_instances_deployed_territory ON unit_instances (deployed_territory_id);

CREATE TABLE unit_research (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL,
    unit_type_id          BIGINT      NOT NULL REFERENCES unit_types(id),
    researched_level      INTEGER     NOT NULL DEFAULT 1,
    pending_level         INTEGER,
    research_complete_at  TIMESTAMP,
    CONSTRAINT uk_unit_research UNIQUE (user_id, unit_type_id)
);

CREATE TABLE attack_tokens (
    user_id          BIGINT   PRIMARY KEY,
    normal_count     INTEGER  NOT NULL DEFAULT 0,
    precision_count  INTEGER  NOT NULL DEFAULT 0,
    CONSTRAINT chk_attack_token_normal_nonnegative CHECK (normal_count >= 0),
    CONSTRAINT chk_attack_token_precision_nonnegative CHECK (precision_count >= 0)
);

CREATE TABLE siege_events (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attacker_id          BIGINT       NOT NULL,
    defender_id          BIGINT       NOT NULL,
    target_territory_id  BIGINT       NOT NULL,
    target_building_id   BIGINT REFERENCES building_instances(id),
    attack_zone          INTEGER      NOT NULL,
    status               VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    siege_start_at       TIMESTAMP    NOT NULL,
    resolve_at           TIMESTAMP    NOT NULL
);

CREATE INDEX idx_siege_events_pending ON siege_events (resolve_at)
    WHERE status = 'PENDING';
CREATE INDEX idx_siege_events_target_territory ON siege_events (target_territory_id);

CREATE TABLE siege_forces (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siege_id      BIGINT   NOT NULL REFERENCES siege_events(id) ON DELETE CASCADE,
    unit_type_id  BIGINT   NOT NULL REFERENCES unit_types(id),
    quantity      INTEGER  NOT NULL,
    level         INTEGER  NOT NULL DEFAULT 1,
    CONSTRAINT uk_siege_force UNIQUE (siege_id, unit_type_id, level),
    CONSTRAINT chk_siege_force_quantity_nonnegative CHECK (quantity >= 0)
);

CREATE TABLE siege_structures (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siege_id  BIGINT       NOT NULL REFERENCES siege_events(id) ON DELETE CASCADE,
    type      VARCHAR(10)  NOT NULL,
    coord_x   INTEGER      NOT NULL,
    coord_y   INTEGER      NOT NULL,
    CONSTRAINT chk_siege_structure_type CHECK (type IN ('STAGING', 'TOWER', 'SUPPLY'))
);

CREATE TABLE siege_results (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siege_id                BIGINT       NOT NULL UNIQUE REFERENCES siege_events(id),
    is_attacker_win         BOOLEAN      NOT NULL,
    attacker_units_lost     INTEGER,
    defender_units_lost     INTEGER,
    looted_gp               INTEGER      NOT NULL DEFAULT 0,
    result_type             VARCHAR(15),
    applied_cooldown_hours  INTEGER
);

CREATE TABLE combat_user_snapshots (
    user_id     BIGINT       PRIMARY KEY,
    nickname    VARCHAR(50)  NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE combat_commands (
    command_key          VARCHAR(200)  PRIMARY KEY,
    command_type         VARCHAR(100)  NOT NULL,
    request_fingerprint  VARCHAR(500)  NOT NULL,
    response_payload     TEXT,
    created_at           TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at         TIMESTAMP
);

CREATE TABLE combat_outbox (
    id             VARCHAR(36)   PRIMARY KEY,
    aggregate_type VARCHAR(100)  NOT NULL,
    aggregate_id   VARCHAR(100)  NOT NULL,
    event_topic    VARCHAR(100)  NOT NULL,
    payload        TEXT          NOT NULL,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at   TIMESTAMP
);

CREATE INDEX idx_combat_outbox_pending ON combat_outbox (created_at)
    WHERE published_at IS NULL;
