-- map-service 초기 스키마. 공유 커널 map 도메인의 8개 테이블을 소유한다.
-- user는 user-service 소유라 FK 없이 식별자(bigint)만 보관한다(owner_id·user_id).
-- continents·territory_grades·territories 내부 FK는 map 소유라 유지한다.

CREATE TABLE continents (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(50) NOT NULL,
    theme_color         VARCHAR(7)  NOT NULL,
    display_name        VARCHAR(50),
    grade               VARCHAR(2),
    min_trophy_required INTEGER,
    description         VARCHAR(100)
);

CREATE TABLE territory_grades (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade                    VARCHAR(1)   NOT NULL UNIQUE,
    production_multiplier    NUMERIC(3,1) NOT NULL,
    auction_price_multiplier NUMERIC(3,1) NOT NULL,
    pre_built_count          INTEGER      NOT NULL DEFAULT 0,
    spawn_rate               NUMERIC(4,3) NOT NULL,
    grid_size                INTEGER      NOT NULL,
    zone1_radius             INTEGER      NOT NULL,
    zone2_radius             INTEGER      NOT NULL
);

CREATE TABLE territories (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coord_x              INTEGER     NOT NULL,
    coord_y              INTEGER     NOT NULL,
    continent_id         BIGINT      REFERENCES continents (id),
    owner_id             BIGINT,
    current_color        VARCHAR(7),
    occupied_until       TIMESTAMP,
    protected_until      TIMESTAMP,
    next_auction_at      TIMESTAMP,
    status               VARCHAR(10) NOT NULL,
    base_production_rate INTEGER     NOT NULL DEFAULT 10,
    auction_enabled      BOOLEAN     NOT NULL DEFAULT TRUE,
    last_produced_at     TIMESTAMP,
    grade_id             BIGINT      REFERENCES territory_grades (id)
);

CREATE INDEX idx_territory_owner ON territories (owner_id);
CREATE INDEX idx_territory_status ON territories (status);
CREATE INDEX idx_territory_continent ON territories (continent_id);
CREATE INDEX idx_territory_next_auction ON territories (status, next_auction_at);

CREATE TABLE bonus_tiles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_id BIGINT       NOT NULL UNIQUE REFERENCES territories (id),
    multiplier   NUMERIC(4,2) NOT NULL,
    description  VARCHAR(100)
);

CREATE TABLE color_histories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_id BIGINT     NOT NULL REFERENCES territories (id),
    user_id      BIGINT     NOT NULL,
    color_code   VARCHAR(7) NOT NULL,
    created_at   TIMESTAMP  NOT NULL
);

CREATE INDEX idx_color_history_territory_user ON color_histories (territory_id, user_id);

CREATE TABLE land_tax_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL,
    territory_count INTEGER     NOT NULL,
    gp_charged      INTEGER     NOT NULL,
    status          VARCHAR(10) NOT NULL,
    charged_at      TIMESTAMP   NOT NULL
);

CREATE INDEX idx_land_tax_user ON land_tax_logs (user_id, charged_at DESC);

CREATE TABLE territory_production_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    territory_id BIGINT      NOT NULL REFERENCES territories (id),
    owner_id     BIGINT      NOT NULL,
    amount       INTEGER     NOT NULL,
    reason       VARCHAR(30) NOT NULL,
    created_at   TIMESTAMP   NOT NULL
);

-- map 읽기 프로젝션 — auction-service 이벤트로만 갱신되는 read-model.
-- 영토당 활성 경매는 하나이므로 territory_id를 PK로 둔다.
CREATE TABLE territory_auction_status (
    territory_id  BIGINT    NOT NULL PRIMARY KEY,
    auction_id    BIGINT    NOT NULL,
    current_price INTEGER   NOT NULL,
    end_at        TIMESTAMP NOT NULL
);

CREATE INDEX idx_territory_auction_status_auction_id
    ON territory_auction_status (auction_id);
