-- admin-service 초기 스키마. 관리자 신원(자체 소유)·설정·감사 로그를 소유한다.
-- 관리자 계정은 게임 users(role=ADMIN)에서 일회성 이관한다(공개 유저 인증과 분리).

CREATE TABLE admin_accounts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    totp_secret   VARCHAR(255),
    role          VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE admin_settings (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(50)  NOT NULL UNIQUE,
    setting_value VARCHAR(255) NOT NULL
);

CREATE TABLE admin_audit_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT      NOT NULL,
    action        VARCHAR(50) NOT NULL,
    target_type   VARCHAR(20),
    target_id     BIGINT,
    detail_json   TEXT,
    created_at    TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE INDEX idx_admin_audit_action ON admin_audit_logs (action, target_type);
