-- social-service 소유 스키마: 채팅(chat_rooms/chat_messages)·관심그룹(interest_groups)·길드(guilds/guild_members)
-- 신원(user)·대륙(continent)은 타 서비스 소유 → FK 없이 *_id(Long)로만 보관.

CREATE TABLE chat_rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(10) NOT NULL,
    target_id   BIGINT
);

CREATE TABLE chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT NOT NULL REFERENCES chat_rooms(id),
    sender_id  BIGINT NOT NULL,
    content    TEXT NOT NULL,
    sent_at    TIMESTAMP NOT NULL
);
CREATE INDEX idx_chat_messages_room_sent ON chat_messages(room_id, sent_at);

CREATE TABLE interest_groups (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    continent_id BIGINT NOT NULL
);

CREATE TABLE guilds (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(20) NOT NULL UNIQUE,
    description       VARCHAR(200),
    emblem            VARCHAR(255),
    master_id         BIGINT NOT NULL,
    max_members       INT NOT NULL DEFAULT 30,
    recruiting_status VARCHAR(6) NOT NULL DEFAULT 'OPEN',
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE guild_members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL REFERENCES guilds(id),
    user_id    BIGINT NOT NULL,
    role       VARCHAR(10) NOT NULL,
    status     VARCHAR(10) NOT NULL,
    message    VARCHAR(200),
    joined_at  TIMESTAMP NOT NULL
);
CREATE INDEX idx_guild_members_guild ON guild_members(guild_id);
CREATE INDEX idx_guild_members_user ON guild_members(user_id);
